# Generated by Django 4.2 on 2023-06-18 17:58

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NewBookName', models.CharField(max_length=150)),
                ('author_book', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('ISBN', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(0)])),
                ('Abstract', models.TextField()),
            ],
            options={
                'verbose_name': 'New_book',
                'verbose_name_plural': 'New_Books',
            },
        ),
    ]
