# Generated by Django 4.2 on 2023-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
