# Generated by Django 4.2 on 2023-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_book', '0002_new_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
