# Generated by Django 4.2 on 2023-06-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New_book', '0003_alter_new_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_book',
            old_name='cover',
            new_name='Cover',
        ),
    ]
